version: '3'

services:
  node:
    build:
      context: ./docker/node
    container_name: befstore-node
    user: "node"
    working_dir: /home/node/app
    env_file: [ .env.development ]
    command: "./docker/node/setup.sh"
    volumes:
      - ./:/home/node/app
      - ./package.json:/home/node/app/package.json
      - ./package-lock.json:/home/node/app/package-lock.json
      - ./.env.development:/home/node/app/.env.development


