import { forms } from '../calculators/constants';

export const fields = {
  nat_gas_input: {
    name: 'input_12',
    id: `input_${forms.householdFormId}_12`,
    desc: 'GOOD natural_gas_total_therms',
    unit: 'therms',
    label: 'nat_gas_input',
  },
  nat_gas_select_input: {
    name: 'input_13[]',
    id: `input_${forms.householdFormId}_13`,
    desc: 'GOOD nat_gas_select_array',
    unit: 'therms',
    label: 'nat_gas_select_input',
  },
  fuel_oil_input: {
    name: 'input_15',
    id: `input_${forms.householdFormId}_15`,
    desc: 'GOOD fuel_oil_total',
    unit: 'gallons',
    label: 'fuel_oil_input',
  },
  fuel_oil_select_input: {
    name: 'input_16[]',
    id: `input_${forms.householdFormId}_16`,
    desc: 'GOOD fuel_oil_select_input',
    unit: 'therms',
    label: 'fuel_oil_select_input',
  },
  propane_input: {
    name: 'input_18',
    id: `input_${forms.householdFormId}_18`,
    desc: 'GOOD propane_total',
    unit: 'gallons',
    label: 'propane_input',
  },
  propane_select_input: {
    name: 'input_19[]',
    id: `input_${forms.householdFormId}_19`,
    desc: 'GOOD propane_select_input',
    unit: 'therms',
    label: 'propane_select_input',
  },
  diet_select_input: {
    name: 'input_79[]',
    id: `input_${forms.householdFormId}_79`,
    desc: 'diet_select_input',
    unit: 'meals',
    label: 'diet_select_input',
  },
  diesel_input: {
    name: 'input_4',
    id: `input_${forms.householdFormId}_4`,
    desc: 'diesel_total',
    unit: 'gallons',
    label: 'diesel_input',
  },
  flight_input: {
    name: 'input_55',
    id: `input_${forms.householdFormId}_55`,
    desc: 'GOOD flight_input',
    unit: 'miles',
    label: 'flight_input',
  },
  flight_select_input: {
    name: 'input_56[]',
    id: `input_${forms.householdFormId}_56`,
    desc: 'GOOD flight_select_input',
    unit: 'miles',
    label: 'flight_select_input',
  },
  water_input: {
    name: 'input_42',
    id: `input_${forms.householdFormId}_42`,
    desc: 'GOOD water_total',
    unit: 'gallons',
    label: 'water_input',
  },
  water_select_input: {
    name: 'input_47',
    id: `input_${forms.householdFormId}_47`,
    desc: 'GOOD household average water_select_input',
    unit: 'gallons',
    label: 'water_select_input',
  },
  lodging_input: {
    name: 'input_64',
    id: `input_${forms.householdFormId}_64`,
    desc: 'GOOD lodging_input',
    unit: 'nights',
    label: 'lodging_input',
  },
  rental_input: {
    name: 'input_65',
    id: `input_${forms.householdFormId}_65`,
    desc: 'GOOD rental_input',
    unit: 'cars',
    label: 'rental_input',
  },
  electricity_input: {
    name: 'input_8',
    id: `input_${forms.householdFormId}_8`,
    desc: 'GOOD electricity_input',
    unit: 'kWh',
    label: 'electricity_input',
  },
  electricity_select_input: {
    name: 'input_9[]',
    id: `input_${forms.householdFormId}_9`,
    desc: 'GOOD electricity_select_input',
    unit: 'kWh',
    label: 'electricity_select_input',
  },
  offsiteServer_input: {
    name: 'input_7',
    id: `input_${forms.householdFormId}_7`,
    desc: 'offsiteServer_input',
    unit: 'number',
    label: 'offsiteServer_input',
  },
  annual_revenue_input: {
    name: 'input_98',
    id: `input_${forms.householdFormId}_98`,
    desc: 'annual revenue',
    unit: 'number',
    label: 'annual_revenue_input',
  },
  name_input: {
    name: 'input_3',
    id: `input_${forms.householdFormId}_3`,
    desc: 'GOOD your name',
    unit: 'name',
    label: 'name_input',
  },
  num_of_employee_input: {
    name: 'input_99',
    id: `input_${forms.householdFormId}_99`,
    desc: 'number of employees',
    unit: 'number',
    label: 'num_of_employee_input',
  },
  zipcode_input: {
    name: 'input_4',
    id: `input_${forms.householdFormId}_4`,
    desc: 'GOOD zip_code',
    unit: 'zip code',
    label: 'zip_code',
  },
};

export const hiddenValues = {
  household_total: {
    name: 'input_34',
    id: `input_${forms.householdFormId}_34`,
    desc: 'total emissions for household calculator',
    units: 'mT',
    label: 'household_total',
  },
  scope1_total: {
    name: 'input_35',
    id: `input_${forms.householdFormId}_35`,
    desc: 'GOOD total emissions for Scope 1 emissions household calculator',
    units: 'mT',
    label: 'scope1_total',
  },
  scope2_total: {
    name: 'input_36',
    id: `input_${forms.householdFormId}_36`,
    desc: 'GOOD total emissions for Scope 2 emissions household calculator',
    units: 'mT',
    label: 'scope2_total',
  },
  scope3_total: {
    name: 'input_37',
    id: `input_${forms.householdFormId}_37`,
    desc: 'GOOD total emissions for Scope 3 emissions household calculator',
    units: 'mT',
    label: 'scope3_total',
  },
  scope4_total: {
    name: 'input_38',
    id: `input_${forms.householdFormId}_38`,
    desc: 'GOOD total emissions for Scope 4 emissions household calculator',
    units: 'mT',
    label: 'scope4_total',
  },
  scope5_total: {
    name: 'input_39',
    id: `input_${forms.householdFormId}_39`,
    desc: 'GOOD total emissions for Scope 5 emissions household calculator',
    units: 'mT',
    label: 'scope5_total',
  },
  annual_nat_gas_total: {
    name: 'input_22',
    id: `input_${forms.householdFormId}_22`,
    desc: 'GOOD total emission for annual nat gas',
    units: 'mT',
    label: 'annual_nat_gas_total',
  },
  select_nat_gas_total: {
    name: 'input_23',
    id: `input_${forms.householdFormId}_23`,
    desc: 'GOOD total emission for select building nat gas',
    units: 'mT',
    label: 'select_nat_gas_total',
  },
  nat_gas_total: {
    name: 'input_24',
    id: `input_${forms.householdFormId}_24`,
    desc: 'GOOD total emission for nat gas',
    units: 'mT',
    label: 'nat_gas_total',
  },
  annual_fuel_oil_total: {
    name: 'input_28',
    id: `input_${forms.householdFormId}_28`,
    desc: 'GOOD total emission for annual fuel oil',
    units: 'mT',
    label: 'annual_fuel_oil_total',
  },
  select_fuel_oil_total: {
    name: 'input_29',
    id: `input_${forms.householdFormId}_29`,
    desc: 'GOOD total emission for select building fuel oil',
    units: 'mT',
    label: 'select_fuel_oil_total',
  },
  fuel_oil_total: {
    name: 'input_30',
    id: `input_${forms.householdFormId}_30`,
    desc: 'GOOD total emission for nat gas',
    units: 'mT',
    label: 'fuel_oil_total',
  },
  annual_propane_total: {
    name: 'input_31',
    id: `input_${forms.householdFormId}_31`,
    desc: 'GOOD total emission for annual propane',
    units: 'mT',
    label: 'annual_propane_total',
  },
  select_propane_total: {
    name: 'input_32',
    id: `input_${forms.householdFormId}_32`,
    desc: 'GOOD total emission for select building propane',
    units: 'mT',
    label: 'select_propane_total',
  },
  propane_total: {
    name: 'input_33',
    id: `input_${forms.householdFormId}_33`,
    desc: 'GOOD total emission for propane gas',
    units: 'mT',
    label: 'propane_total',
  },
  car_total: {
    name: '71',
    id: `input_${forms.householdFormId}_71`,
    desc: 'GOOD total emission for car',
    units: 'mT',
    label: 'car_total',
  },
  hybrid_car_total: {
    name: 'input_72',
    id: `input_${forms.householdFormId}_72`,
    desc: 'GOOD total emission for hybrid car',
    units: 'mT',
    label: 'hybrid_car_total',
  },
  electric_vehicle_total: {
    name: 'input_73',
    id: `input_${forms.householdFormId}_73`,
    desc: 'GOOD total emission for electric car',
    units: 'mT',
    label: 'electric_vehicle_total',
  },
  pickup_truck_van_total: {
    name: 'input_74',
    id: `input_${forms.householdFormId}_74`,
    desc: 'GOOD total emission for pickup and vans',
    units: 'mT',
    label: 'pickup_truck_van_total',
  },
  annual_water_total: {
    name: 'input_76',
    id: `input_${forms.householdFormId}_76`,
    desc: 'GOOD annual total water gallons',
    units: 'gallons',
    label: 'annual_water_total',
  },
  select_water_total: {
    name: 'input_77',
    id: `input_${forms.householdFormId}_77`,
    desc: 'GOOD total household average water gallons',
    units: 'gallons',
    label: 'select_water_total',
  },
  water_total: {
    name: 'input_75',
    id: `input_${forms.householdFormId}_75`,
    desc: 'GOOD total water gallons',
    units: 'gallons',
    label: 'water_total',
  },
  personalVehicle_total: {
    name: 'input_52',
    id: `input_${forms.householdFormId}_52`,
    desc: 'GOOD total personal household vehicle emissions',
    units: 'mT',
    label: 'personalVehicle_total',
  },
  commuting_total: {
    name: 'input_85',
    id: `input_${forms.householdFormId}_85`,
    desc: 'total commuting emissions',
    units: 'mT',
    label: 'commuting_total',
  },
  diesel_total: {
    name: 'input_83',
    id: `input_${forms.householdFormId}_83`,
    desc: 'total emission for diesel',
    units: 'mT',
    label: 'diesel_total',
  },
  annual_electricity_total: {
    name: 'input_25',
    id: `input_${forms.householdFormId}_25`,
    desc: 'GOOD total emission for annual electricity',
    units: 'mT',
    label: 'annual_electricity_total',
  },
  select_electricity_total: {
    name: 'input_26',
    id: `input_${forms.householdFormId}_26`,
    desc: 'GOOD total emission for select building electricity',
    units: 'mT',
    label: 'select_electricity_total',
  },
  electricity_total: {
    name: 'input_27',
    id: `input_${forms.householdFormId}_27`,
    desc: 'GOOD total emission for electricity',
    units: 'mT',
    label: 'electricity_total',
  },
  offsiteServer_total: {
    name: 'input_89',
    id: `input_${forms.householdFormId}_89`,
    desc: 'total emission for servers',
    units: 'kW',
    label: 'offsiteServer_total',
  },
  annual_flight_total: {
    name: 'input_59',
    id: `input_${forms.householdFormId}_59`,
    desc: 'GOOD total emission for annual flights',
    units: 'miles',
    label: 'annual_flight_total',
  },
  select_flight_total: {
    name: 'input_60',
    id: `input_${forms.householdFormId}_60`,
    desc: 'GOOD total emission for select flights',
    units: 'miles',
    label: 'select_flight_total',
  },
  table_flight_total: {
    name: 'input_61',
    id: `input_${forms.householdFormId}_61`,
    desc: 'GOOD total emission for haul flights',
    units: 'miles',
    label: 'table_flight_total',
  },
  flight_total: {
    name: 'input_62',
    id: `input_${forms.householdFormId}_62`,
    desc: 'GOOD total emission for flight travel',
    units: 'miles',
    label: 'flight_total',
  },
  lodging_total: {
    name: 'input_66',
    id: `input_${forms.householdFormId}_66`,
    desc: 'GOOD total emission for lodging',
    units: 'nights',
    label: 'lodging_total',
  },
  rental_total: {
    name: 'input_67',
    id: `input_${forms.householdFormId}_67`,
    desc: 'GOOD total emission for rental cars',
    units: 'cars',
    label: 'rental_total',
  },
  select_diet_total: {
    name: 'input_81',
    id: `input_${forms.householdFormId}_81`,
    desc: 'total food emission from table',
    units: 'mT',
    label: 'select_diet_total',
  },
  diet_total: {
    name: 'input_70',
    id: `input_${forms.householdFormId}_70`,
    desc: 'GOOD total diet calculation',
    units: 'mT',
    label: 'diet_total',
  },
  annual_waterWRC_total: {
    name: 'input_44',
    id: `input_${forms.householdFormId}_44`,
    desc: 'GOOD total annual water WRC',
    units: 'gallons',
    label: 'annual_waterWRC_total',
  },
  select_waterWRC_total: {
    name: 'input_45',
    id: `input_${forms.householdFormId}_45`,
    desc: 'GOOD total building waterWRC',
    units: 'gallons',
    label: 'select_waterWRC_total',
  },
  wrc_water: {
    name: 'input_46',
    id: `input_${forms.householdFormId}_46`,
    desc: 'GOOD total emission for water usage',
    units: 'mT',
    label: 'wrc_water',
  },
  rec_electricity: {
    name: 'input_40',
    id: `input_${forms.householdFormId}_40`,
    desc: 'GOOD recs for electricty ',
    units: 'REC',
    label: 'rec_electricity',
  },
  rec_offsiteServer: {
    name: 'input_107',
    id: `input_${forms.householdFormId}_107`,
    desc: 'recs for offsite servers',
    units: 'REC',
    label: 'rec_offsiteServer',
  },
  egrid: {
    name: 'input_10',
    id: `input_${forms.householdFormId}_10`,
    desc: 'GOOD egrid value from zipcode',
    units: 'CODE',
    label: 'egrid',
  },
};
