import { forms } from '../calculators/constants';

export const fields = {
  nat_gas_input: {
    name: 'input_19',
    id: `input_${forms.businessFormId}_19`,
    desc: 'natural_gas_total_therms',
    unit: 'therms',
    label: 'nat_gas_input',
  },
  nat_gas_select_input: {
    name: 'input_63[]',
    id: `input_${forms.businessFormId}_63`,
    desc: 'nat_gas_select_array',
    unit: 'therms',
    label: 'nat_gas_select_input',
  },
  fuel_oil_select_input: {
    name: 'input_64[]',
    id: `input_${forms.businessFormId}_64`,
    desc: 'fuel_oil_select_input',
    unit: 'therms',
    label: 'fuel_oil_select_input',
  },
  fuel_oil_input: {
    name: 'input_20',
    id: `input_${forms.businessFormId}_20`,
    desc: 'fuel_oil_total',
    unit: 'gallons',
    label: 'fuel_oil_input',
  },
  propane_input: {
    name: 'input_3',
    id: `input_${forms.businessFormId}_3`,
    desc: 'propane_total',
    unit: 'gallons',
    label: 'propane_input',
  },
  diesel_input: {
    name: 'input_4',
    id: `input_${forms.businessFormId}_4`,
    desc: 'diesel_total',
    unit: 'gallons',
    label: 'diesel_input',
  },
  flight_input: {
    name: 'input_14',
    id: `input_${forms.businessFormId}_14`,
    desc: 'flight_input',
    unit: 'miles',
    label: 'flight_input',
  },
  flight_select_input: {
    name: 'input_73[]',
    id: `input_${forms.businessFormId}_73`,
    desc: 'flight_select_input',
    unit: 'miles',
    label: 'flight_select_input',
  },
  water_input: {
    name: 'input_30',
    id: `input_${forms.businessFormId}_30`,
    desc: 'water_total',
    unit: 'gallons',
    label: 'water_input',
  },
  water_select_input: {
    name: 'input_72[]',
    id: `input_${forms.businessFormId}_72`,
    desc: 'water_select_input',
    unit: 'gallons',
    label: 'water_select_input',
  },
  lodging_input: {
    name: 'input_12',
    id: `input_${forms.businessFormId}_12`,
    desc: 'lodging_input',
    unit: 'nights',
    label: 'lodging_input',
  },
  rental_input: {
    name: 'input_13',
    id: `input_${forms.businessFormId}_13`,
    desc: 'rental_input',
    unit: 'cars',
    label: 'rental_input',
  },
  electricity_input: {
    name: 'input_21',
    id: `input_${forms.businessFormId}_21`,
    desc: 'electricity_input',
    unit: 'kWh',
    label: 'electricity_input',
  },
  electricity_select_input: {
    name: 'input_71[]',
    id: `input_${forms.businessFormId}_71`,
    desc: 'electricity_select_input',
    unit: 'kWh',
    label: 'electricity_select_input',
  },
  offsiteServer_input: {
    name: 'input_7',
    id: `input_${forms.businessFormId}_7`,
    desc: 'offsiteServer_input',
    unit: 'number',
    label: 'offsiteServer_input',
  },
  annual_revenue_input: {
    name: 'input_98',
    id: `input_${forms.businessFormId}_98`,
    desc: 'annual revenue',
    unit: 'number',
    label: 'annual_revenue_input',
  },
  company_name_input: {
    name: 'input_96',
    id: `input_${forms.businessFormId}_96`,
    desc: 'company name',
    unit: 'name',
    label: 'company_name_input',
  },
  num_of_employee_input: {
    name: 'input_99',
    id: `input_${forms.businessFormId}_99`,
    desc: 'number of employees',
    unit: 'number',
    label: 'num_of_employee_input',
  },
  zipcode_input: {
    name: 'input_102',
    id: `input_${forms.businessFormId}_102`,
    desc: 'zip_code',
    unit: 'zip code',
    label: 'zip_code',
  },
};

export const hiddenValues = {
  business_total: {
    name: 'input_76',
    id: `input_${forms.businessFormId}_76`,
    desc: 'total emissions for business calculator',
    units: 'mT',
    label: 'business_total',
  },
  scope1_total: {
    name: 'input_86',
    id: `input_${forms.businessFormId}_86`,
    desc: 'total emissions for Scope 2 emissions business calculator',
    units: 'mT',
    label: 'scope1_total',
  },
  scope2_total: {
    name: 'input_87',
    id: `input_${forms.businessFormId}_87`,
    desc: 'total emissions for Scope 2 emissions business calculator',
    units: 'mT',
    label: 'scope2_total',
  },
  scope3_total: {
    name: 'input_88',
    id: `input_${forms.businessFormId}_88`,
    desc: 'total emissions for Scope 3 emissions business calculator',
    units: 'mT',
    label: 'scope3_total',
  },
  annual_nat_gas_total: {
    name: 'input_108',
    id: `input_${forms.businessFormId}_108`,
    desc: 'total emission for annual nat gas',
    units: 'mT',
    label: 'annual_nat_gas_total',
  },
  select_nat_gas_total: {
    name: 'input_109',
    id: `input_${forms.businessFormId}_109`,
    desc: 'total emission for select building nat gas',
    units: 'mT',
    label: 'select_nat_gas_total',
  },
  nat_gas_total: {
    name: 'input_75',
    id: `input_${forms.businessFormId}_75`,
    desc: 'total emission for nat gas',
    units: 'mT',
    label: 'nat_gas_total',
  },
  annual_fuel_oil_total: {
    name: 'input_110',
    id: `input_${forms.businessFormId}_110`,
    desc: 'total emission for annual fuel oil',
    units: 'mT',
    label: 'annual_fuel_oil_total',
  },
  select_fuel_oil_total: {
    name: 'input_111',
    id: `input_${forms.businessFormId}_111`,
    desc: 'total emission for select building fuel oil',
    units: 'mT',
    label: 'select_fuel_oil_total',
  },
  fuel_oil_total: {
    name: 'input_81',
    id: `input_${forms.businessFormId}_81`,
    desc: 'total emission for nat gas',
    units: 'mT',
    label: 'fuel_oil_total',
  },
  propane_total: {
    name: 'input_82',
    id: `input_${forms.businessFormId}_82`,
    desc: 'total emission for propane gas',
    units: 'mT',
    label: 'propane_total',
  },
  ownedVehicle_total: {
    name: 'input_84',
    id: `input_${forms.businessFormId}_84`,
    desc: 'total owned vehicle fleet emissions',
    units: 'mT',
    label: 'ownedVehicle_total',
  },
  commuting_total: {
    name: 'input_85',
    id: `input_${forms.businessFormId}_85`,
    desc: 'total commuting emissions',
    units: 'mT',
    label: 'commuting_total',
  },
  diesel_total: {
    name: 'input_83',
    id: `input_${forms.businessFormId}_83`,
    desc: 'total emission for diesel',
    units: 'mT',
    label: 'diesel_total',
  },
  annual_electricity_total: {
    name: 'input_112',
    id: `input_${forms.businessFormId}_112`,
    desc: 'total emission for annual electricity',
    units: 'mT',
    label: 'annual_electricity_total',
  },
  select_electricity_total: {
    name: 'input_113',
    id: `input_${forms.businessFormId}_113`,
    desc: 'total emission for select building electricity',
    units: 'mT',
    label: 'select_electricity_total',
  },
  electricity_total: {
    name: 'input_105',
    id: `input_${forms.businessFormId}_105`,
    desc: 'total emission for electricity',
    units: 'mT',
    label: 'electricity_total',
  },
  offsiteServer_total: {
    name: 'input_89',
    id: `input_${forms.businessFormId}_89`,
    desc: 'total emission for servers',
    units: 'kW',
    label: 'offsiteServer_total',
  },
  annual_flight_total: {
    name: 'input_116',
    id: `input_${forms.businessFormId}_116`,
    desc: 'total emission for annual flights',
    units: 'miles',
    label: 'annual_flight_total',
  },
  select_flight_total: {
    name: 'input_117',
    id: `input_${forms.businessFormId}_117`,
    desc: 'total emission for select flights',
    units: 'miles',
    label: 'select_flight_total',
  },
  table_flight_total: {
    name: 'input_118',
    id: `input_${forms.businessFormId}_118`,
    desc: 'total emission for haul flights',
    units: 'miles',
    label: 'table_flight_total',
  },
  flight_total: {
    name: 'input_106',
    id: `input_${forms.businessFormId}_106`,
    desc: 'total emission for flight travel',
    units: 'miles',
    label: 'flight_total',
  },
  lodging_total: {
    name: 'input_119',
    id: `input_${forms.businessFormId}_119`,
    desc: 'total emission for lodging',
    units: 'nights',
    label: 'lodging_total',
  },
  rental_total: {
    name: 'input_120',
    id: `input_${forms.businessFormId}_120`,
    desc: 'total emission for rental cars',
    units: 'cars',
    label: 'rental_total',
  },
  wrc_water: {
    name: 'input_92',
    id: `input_${forms.businessFormId}_92`,
    desc: 'total emission for water usage',
    units: 'mT',
    label: 'wrc_water',
  },
  annual_waterWRC_total: {
    name: 'input_114',
    id: `input_${forms.businessFormId}_114`,
    desc: 'total annual water WRC',
    units: 'gallons',
    label: 'annual_waterWRC_total',
  },
  select_waterWRC_total: {
    name: 'input_115',
    id: `input_${forms.businessFormId}_115`,
    desc: 'total building waterWRC',
    units: 'gallons',
    label: 'select_waterWRC_total',
  },
  rec_electricity: {
    name: 'input_91',
    id: `input_${forms.businessFormId}_91`,
    desc: 'recs for electricty servers',
    units: 'REC',
    label: 'rec_electricity',
  },
  rec_offsiteServer: {
    name: 'input_107',
    id: `input_${forms.businessFormId}_107`,
    desc: 'recs for offsite servers',
    units: 'REC',
    label: 'rec_offsiteServer',
  },
  egrid: {
    name: 'input_104',
    id: `input_${forms.businessFormId}_104`,
    desc: 'egrid value from zipcode',
    units: 'CODE',
    label: 'egrid',
  },
};
